@echo off
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\3vars.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\5vars.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\9sym_d.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\carry.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\con1f1.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\con2f2.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\exam1_d.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\exam3_d.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\max46_d.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\newill_d.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\newtag_d.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\rd53f1.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\rd53f2.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\rd53f3.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\rd73f1.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\rd73f2.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\rd73f3.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\rd84f1.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\rd84f2.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\rd84f3.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\rd84f4.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\sao2f1.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\sao2f2.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\sao2f3.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\sao2f4.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\sym10_d.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\t481_d.pla
java -cp build\classes MemristorsTANT.MemristorsTANT benchmarks\xor5_d.pla
